version: "3.3"
services:
  wordpress:
    image: "wordpress:${WP_VERSION:-5.0.3}-php${PHP_VERSION:-7.2}-apache"
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: "mysql"
      WORDPRESS_DB_NAME: "wordpress"
      WORDPRESS_DB_PASSWORD: "testing"
      WORDPRESS_DB_USER: "root"
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_DEBUG', true );
    volumes:
      - "./_dev/wp-graphql:/var/www/html/wp-content/plugins/wp-graphql"
      - "./_dev/wp-graphiql:/var/www/html/wp-content/plugins/wp-graphiql"
      - "./_dev/wp-graphql-jwt-authentication:/var/www/html/wp-content/plugins/wp-graphql-jwt-authentication"
      - "./build/plugin:/var/www/html/wp-content/plugins/oil-based"
      - "./build/theme:/var/www/html/wp-content/themes/oil-based"
    restart: always
    ports:
      - 8080:80
  mysql:
    image: "mariadb:10.2"
    environment:
      MYSQL_DATABASE: "wordpress"
      MYSQL_ROOT_PASSWORD: "testing"
